"""empty message

Revision ID: e0c31604cc03
Revises: 05ccdf249e51
Create Date: 2023-07-07 20:51:11.957496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0c31604cc03'
down_revision = '05ccdf249e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('wallet')

    op.create_table('wallet',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('balance', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='wallet_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
